version: "3.9"
services:
  app:
    container_name: mvc_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
  db:
    container_name: mssql-2019
    build: ./Docker
    ports:
      - "1433:1433"
    volumes:
      - Docker:/var/lib/mssql/data

volumes:
  Docker: 